fun main(args:Array<String>){
    var num:Int = readLine()!!.toInt()
    println(num)
    var hundrad = num.div(100)
    num =  num.minus(hundrad*100)
    var fifty = num.div(50)
    num =num.minus(fifty*50)
    var twt = num.div(20)
    num = num.minus(twt *20)
    var ten = num.div(10)
    num = num.minus(ten*10)
    var five = num.div(5)
    num = num.minus(five*5)
    var two = num.div(2)
    num = num.minus(two*2)
    var one = num.div(1)
    println("$hundrad nota(s) de R\$ 100,00")
    println("$fifty nota(s) de R\$ 50,00")
    println("$twt nota(s) de R\$ 20,00")
    println("$ten nota(s) de R\$ 10,00")
    println("$five nota(s) de R\$ 5,00")
    println("$two nota(s) de R\$ 2,00")
    println("$one nota(s) de R\$ 1,00")

}