fun main(args:Array<String>){
    var num:Double = readLine()!!.toDouble().times(100.0)
    println(num)
    var hundrad = num.toInt().div(10000)
    num =  num.minus(hundrad*10000)
    var fifty = num.toInt().div(5000)
    num =num.minus(fifty*5000)
    var twt = num.toInt().div(2000)
    num = num.minus(twt *2000)
    var ten = num.toInt().div(1000)
    num = num.minus(ten*1000)
    var five = num.toInt().div(500)
    num = num.minus(five*500)
    var two = num.toInt().div(200)
    num = num.minus(two*200)
    var one = num.toInt().div(100)
    num = num.minus(one*100)
    var f = num.toInt().div(50)
    num = num.minus(f*50)
    var tf = num.toInt().div(25)
    num = num.minus(tf * 25)
    var tt = num.toInt().div(10)
    num = num.minus(tt*10)
    var ff = num.toInt().div(5)
    num = num.minus(ff*5)
    var oo =  num.toInt().div(1)
    println("NOTAS:")
    println("$hundrad nota(s) de R\$ 100,00")
    println("$fifty nota(s) de R\$ 50,00")
    println("$twt nota(s) de R\$ 20,00")
    println("$ten nota(s) de R\$ 10,00")
    println("$five nota(s) de R\$ 5,00")
    println("$two nota(s) de R\$ 2,00")
    println("MOEDAS:")
    println("$one moeda(s) de R\$ 1.00")
    println("$f moeda(s) de R\$ 0.50")
    println("$tf moeda(s) de R\$ 0.25")
    println("$tt moeda(s) de R\$ 0.10")
    println("$ff moeda(s) de R\$ 0.05")
    println("$oo moeda(s) de R\$ 0.01")
}